# baseURL = "https://example.com/"
baseURL = "https://dycoai.github.io/"
# languageCode = "en-us"
# title = "DyCoAI Research"
title = "DyCoAI Research"
theme = "hugo-PaperMod"

[pagination]
  pagerSize = 6

[params]
  math = true
  ShowShareButtons = true
  ShowReadingTime = true 
  ShowToc = true 
  ShowBreadCrumbs = true 
  ShowPostnavLinks = true 
  ShowCodeCopyButtons = true 
  ShowRelatedPosts = true 
  # disableThemeToggle = true

# [params.homeInfoParams]
# Title = "Dynamical · Collaborative · Agentic"
# Content = "Dynamical · Collaborative · Agentic"

# [[params.socialIcons]]
#   name = "github"
#   url = "https://github.com/yourusername"
# [[params.socialIcons]]
#   name = "twitter"
#   url = "https://twitter.com/yourusername"
# [[params.socialIcons]]
#   name = "linkedin"
#   url = "https://linkedin.com/in/yourusername"

[menu]
  [[menu.main]]
    identifier = "resume-templates"
    name = "Resume Templates"
    url = "/resume-templates/"
    weight = 40
  [[menu.main]]
    identifier = "articles"
    name = "Articles"
    url = "/articles"
    weight = 30 
  [[menu.main]]
    identifier = "occupation-map"
    name = "Occupation Map"
    url = "/occupation-map/"
    weight = 20
  [[menu.main]]
    identifier = "working-with-agentic-ai"
    name = "Agentic Jobs"
    url = "/tags/working-with-agentic-ai/"
    weight = 10
# [[menu.main]]
#   identifier = "posts"
#   name = "Posts"
#   url = "/posts/"
#   weight = 30
# [[menu.main]]
#   identifier = "search"
#   name = "Search"
#   url = "/search/"
#   weight = 40
# [[menu.main]]
#   identifier = "tags"
#   name = "Tags"
#   url = "/tags/"
#   weight = 50
# [[menu.main]]
#   identifier = "about"
#   name = "About"
#   url = "/about/"
#   weight = 30

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
  [markup.highlight]
    noClasses = false
